BINS=_list_partitions.py telegraf_collector_custom_diskio.py telegraf_collector_custom_netstat.py telegraf_collector_custom_netio.py

include root.mk
include $(MFEXT_HOME)/share/subdir_root.mk
include $(MFEXT_HOME)/opt/misc/share/startup_scripts_profiles.mk

all:: profiles $(PREFIX)/bin/cronwrap.sh $(PREFIX)/bin/mfsysmon.status $(PREFIX)/bin/mfsysmon.start $(PREFIX)/bin/mfsysmon.stop $(PREFIX)/bin/mfsysmon.init load_env
