CONFIGS=config.ini mflog_override.conf

include ../adm/root.mk
include $(MFEXT_HOME)/share/subdir_root.mk
include $(MFEXT_HOME)/opt/misc/share/config_subdir.mk

all:: $(MFMODULE_HOME)/config/telegraf.conf $(MFMODULE_HOME)/config/circus.ini
